{"uuid":"8eeac921-4635-47d1-aa91-86beeaa65c4f","historyId":"7db083e5233615a4a51b702f22aaaccb","fullName":"com.effort.nxt.test.WorkProcessCreationTest.validateCreateProcess","labels":[{"name":"package","value":"com.effort.nxt.test.WorkProcessCreationTest"},{"name":"testClass","value":"com.effort.nxt.test.WorkProcessCreationTest"},{"name":"testMethod","value":"validateCreateProcess"},{"name":"parentSuite","value":"Effort NXT Automation"},{"name":"suite","value":"Login"},{"name":"subSuite","value":"com.effort.nxt.test.WorkProcessCreationTest"},{"name":"host","value":"DESKTOP-F48LRL5"},{"name":"thread","value":"14164@DESKTOP-F48LRL5.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"story","value":"Test Case #4, Validate Process"},{"name":"severity","value":"blocker"}],"links":[],"name":"Validating Created Process Spec","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [New Automation _20230102_194654] but found [New automation _20230102_194654]","trace":"java.lang.AssertionError: expected [New Automation _20230102_194654] but found [New automation _20230102_194654]\r\n\tat org.testng.Assert.fail(Assert.java:99)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1037)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:140)\r\n\tat org.testng.Assert.assertEquals(Assert.java:122)\r\n\tat org.testng.Assert.assertEquals(Assert.java:629)\r\n\tat org.testng.Assert.assertEquals(Assert.java:639)\r\n\tat com.effort.nxt.WorkProcessCreation.clickOnProcessWebApp(WorkProcessCreation.java:289)\r\n\tat com.effort.nxt.test.WorkProcessCreationTest.validateCreateProcess(WorkProcessCreationTest.java:88)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)\r\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)\r\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)\r\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:764)\r\n\tat org.testng.TestRunner.run(TestRunner.java:585)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:384)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:286)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1140)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1069)\r\n\tat org.testng.TestNG.run(TestNG.java:1037)\r\n\tat org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)\r\n\tat org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)\r\n\tat org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)\r\n"},"stage":"finished","description":"Test Case #3, Validate Created Process","steps":[],"attachments":[],"parameters":[{"name":"siteURL","value":"https://secure.spoors.io/effortx/login"},{"name":"browser","value":"Chrome"}],"start":1672669066293,"stop":1672669074627}